### ISSUE TITLE
Ooooo I like this!

### ISSUE THREAD

**Issue by csf30816** [ateesdalejr/maildiscuss#1]
What will it be in PHP? Python? JS?

**Comment by ateesdalejr** [comment]
PHP Would be preferable because of frvp.cf. Can we use multiple FTP accounts?

**Comment by csf30816** [comment]
Nah, only one...

**Comment by ateesdalejr** [comment]
My basic idea for this right now is a mailing list so we can communicate easier.

**Comment by csf30816** [comment]
I don't exactly know what you mean. Do you mean a chat or email?

**Comment by ateesdalejr** [comment]
It would be a mix between both.

**Comment by ateesdalejr** [comment]
Kind of like <https://mail.python.org/mailman/listinfo/python-ideas> but much nicer looking.

**Comment by csf30816** [comment]
Ah, ok. So kinda like if your not there and I send you a message it sends you an email?

**Comment by ateesdalejr** [comment]
@csf30816 Yup. You got it.

**Comment by ateesdalejr** [comment]
Sort of based off of git issues and mailing lists combined.

**Comment by csf30816** [comment]
Cool, that should be a little bit easy but also some aspects a challenge (just what I like)

**Comment by ateesdalejr** [comment]
How should the dev process go? Something like this maybe?
* Push to github
* Push git repo to ftp

**Comment by csf30816** [comment]
Yep, unless there are passwords or something... Should we use SQL or JSON?

**Comment by ateesdalejr** [comment]
We can use JSON I guess. I'm not good at SQL. It shouldn't be to read write intensive I don't think.

**Comment by csf30816** [comment]
OK, that's settled than. It should not make things too difficult. We just make a dir called users and make a JSON with that users info and messages and who they are from :)

**Comment by ateesdalejr** [comment]
Sounds simple enough. I can push the changes to my domain for now.

**Comment by csf30816** [comment]
OK

**Comment by ateesdalejr** [comment]
I'm also installing php right now so I can test changes locally.

**Comment by csf30816** [comment]
Coooool

**Comment by csf30816** [comment]
Although http://phpfiddle.org/ is good for that tooo...

**Comment by ateesdalejr** [comment]
If you want to get started I'll try to get back in a few minutes or so because I need to restart my machine.

**Comment by csf30816** [comment]
OK

**Comment by csf30816** [comment]
I am gonna have to setup a freevp server becuz I don't have PHP on my device

**Comment by ateesdalejr** [comment]
@csf30816 Back sorry for the delay.

**Comment by csf30816** [comment]
Oh, no problem. I have time to waste On all day today

**Comment by csf30816** [comment]
I was busy chatting with french wiki peeps, I had no idea what they were saying :P

**Comment by ateesdalejr** [comment]
That sounds fun. 📦 Pushed to the repo already. It doesn't really do anything yet though. brb

**Comment by redmangospros** [comment]
can anyone use this?

**Comment by csf30816** [comment]
Why hello there internet stalker :P It does not work yet, so no

**Comment by csf30816** [comment]
Working on the format for the json file

**Comment by ateesdalejr** [comment]
kk.

**Comment by csf30816** [comment]
```
[
    "csf30816": {
        "name": "csf30816",
        "email": "my@email.address",
        "ip": "12.345.67.890",
        "lastLogin": "12/1/2017 1115UST",
        "messages": [
            {
                "from": "TheUltimatum",
                "date": "12/1/2017 2036UST",
                "mesg": "Hi there :emoji:",
                "file": "./path/to/file.jpg"
            }
        ]
    },
    "TheUltimatum": {...You get the idea...}
]
```
What do you think?

**Comment by csf30816** [comment]
CANT WAIT TILL THE MISSILE ALERT GETS TESTED TODAY!!!

**Comment by ateesdalejr** [comment]
@csf30816 Hope you stay safe down there. 📦 I'm not much safer than you are up here in washington.

**Comment by csf30816** [comment]
Yeah, they can now hit all the coasts :P

**Comment by ateesdalejr** [comment]
That format looks good enough. We can always expand it later.

**Comment by csf30816** [comment]
Are they doing a missile alert test there too?

**Comment by ateesdalejr** [comment]
Can you please look at #2?

**Comment by ateesdalejr** [comment]
No they aren't doing any here that I know of.

**Comment by csf30816** [comment]
ok

**Comment by csf30816** [comment]
Finsihed the thingy

**Comment by csf30816** [comment]
```
{
    "csf30816": {
        "name": "csf30816",
        "email": "my@email.address",
        "ip": "12.345.67.890",
        "lastLogin": "12/1/2017 1115UST",
        "messages": [
            {
                "from": "TheUltimatum",
                "date": "12/1/2017 2036UST",
                "mesg": "Hi there :emoji:",
                "file": "./path/to/file.jpg"
            }
        ]
    },
    "TheUltimatum": {...You get the idea...}
}
```
What do you think? [UPDATED]

**Comment by ateesdalejr** [comment]
@csf30816 That looks good. I'm working on a router thing that will make our lives easier for now.

**Comment by csf30816** [comment]
OK, I am working on that json and getting results with PHP, pretty fun to do 📦

**Comment by csf30816** [comment]
Since I am admin to FRVP I can access the VistaPanel and help

**Comment by ateesdalejr** [comment]
ok that's cool. :) Progress so far is at <andrewjr.frvp.cf>

**Comment by csf30816** [comment]
Awesome! Well I am confidant in this JSON design it works well with PHP. I setup a little thing that has fake messages and it reads them from the JSON and echo's them xD

**Comment by csf30816** [comment]
http://andrewjr.frvp.cf/posts.php TADA

**Comment by ateesdalejr** [comment]
@csf30816 That looks awesome! 💃

**Comment by csf30816** [comment]
Thanks :)

**Comment by ateesdalejr** [comment]
We need to write a module that accesses the json database and allows you to edit it.

**Comment by csf30816** [comment]
Yes, I could work on that I guess :)

**Comment by ateesdalejr** [comment]
OK cool.

**Comment by csf30816** [comment]
Sorry, had to eat back now 👍

**Comment by ateesdalejr** [comment]
Totally fine. So far I've added a protected directory for you to put libraries in. Everything rewrites and redirects to the index.php file so that It can route things.

**Comment by csf30816** [comment]
That's cool! I am trying to make that JSON thing :)

**Comment by ateesdalejr** [comment]
@csf30816 I've got to go for a while. Be back later.

**Comment by csf30816** [comment]
Ok cya

**Comment by csf30816** [comment]
Ugh, i did not save and lost all my work :(

**Comment by csf30816** [comment]
Yay! I think I made something to make users just need to test it!

**Comment by ateesdalejr** [comment]
@csf30816 Cool! 👍 I'm back now.

**Comment by csf30816** [comment]
YAY

**Comment by csf30816** [comment]
Working on Pickel Guy right now though 📦

**Comment by ateesdalejr** [comment]
What's Pickel Guy?

**Comment by csf30816** [comment]
lol it's an animation I was working on :P

**Comment by csf30816** [comment]
Closing this
