### ISSUE TITLE
How to use htaccess to rewrite urls?

### ISSUE THREAD

**Issue by ateesdalejr** [ateesdalejr/maildiscuss#2]
@csf30816 I'm not a PHP or apache pro but how would I rewrite a url from example.com/url/tothing to this: example.com/index.php?route=/url/tothing

**Comment by redmangospros** [comment]
?

**Comment by csf30816** [comment]
Ok. Making the code might not work though :)

**Comment by ateesdalejr** [comment]
@csf30816 What do you mean?

**Comment by csf30816** [comment]
```
RewriteEngine On
RewriteBase /user/
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)$ index.php?user=$1 [L,QSA]
```
This is the code I used for one of my old sites. It redirects from `./user/me` to `./index.php?user=me`. It should work still, and for what you need :)

**Comment by csf30816** [comment]
I don't know if it would work for `./user/me/file` (`./user/index.php?user=me/file`) I could change it to your needs also instead of the `/user/me` thing

**Comment by ateesdalejr** [comment]
I've figured it out check this: <http://andrewjr.frvp.cf/hi>

**Comment by csf30816** [comment]
Oh that's nice :)
