### ISSUE TITLE
Use this to chat

### ISSUE THREAD

**Issue by csf30816** [ateesdalejr/maildiscuss#3]
hi

**Comment by ateesdalejr** [comment]
Hello! :)

**Comment by ateesdalejr** [comment]
We need a simpler project I think. :/

**Comment by csf30816** [comment]
Hi!!!

**Comment by csf30816** [comment]
Yes, this is actually really harder than I thought it would be :(

**Comment by ateesdalejr** [comment]
Agreed. Maybe move onto something less complicated for now?

**Comment by csf30816** [comment]
Yes, I am making WaveCurrent right now :) But I would be happy to help you with whatever 👍

**Comment by ateesdalejr** [comment]
What's WaveCurrent?

**Comment by csf30816** [comment]
Oh, it is a stupid thing I came up with a while ago to check the weather and current news in one app, for Android of course .

**Comment by ateesdalejr** [comment]
Ah. I tried doing some android a while ago. Java just isn't my thing.

**Comment by csf30816** [comment]
I write it in HTML and JS and than use PhoneGap to build it :)

**Comment by ateesdalejr** [comment]
Cool. 👍

**Comment by csf30816** [comment]
Yup, I have the weather working just need to add news :)

**Comment by csf30816** [comment]
Do you have an Android device?

**Comment by ateesdalejr** [comment]
No. I don't own a phone. Don't have the money to pay for my own plan yet.

**Comment by csf30816** [comment]
Yes, my parents decided I needed one even though I never thought much of it. They have an unlimited texting plan they let me have, although I mostly just use it for developing and turn off the data :)

**Comment by csf30816** [comment]
hi

**Comment by ateesdalejr** [comment]
@csf30816 I've made it work nicely now. 👍 <http://andrewjr.frvp.cf/>

**Comment by ateesdalejr** [comment]
I've heard about them. I didn't want to use them because I like cookies. Also cookies are usable from js.

**Comment by ateesdalejr** [comment]
@csf30816 Use this? https://tlk.io/maildiscuss

**Comment by csf30816** [comment]
Ok, let's use that :)
