### ISSUE TITLE
Profile button + more

### ISSUE THREAD

**Issue by csf30816** [ateesdalejr/maildiscuss#4]
There should be a profile button :) Also we should add the settings page to the users profile when they are logged in and we should send requests via JS. But so far this looks really good I like the thought and effort that went into that backend :)

**Comment by ateesdalejr** [comment]
I agree on the profile button. We can use a seperate database for messages and stuff to decrease the chances of race conditions.

The backend was sort of thrown together. There are a few bugs where `addslashes` won't escape single quotes. So it will crash the database script. I need to write my own escaping function for that to work though. Feel free to spice up the ui. I tried to do the bare minimum for now.

**Comment by csf30816** [comment]
Nice, we should not let users set HTML on their bio because they could put some PHP in there and have the server run it. We should do `htmlspecialchars()` in PHP to replace characters with HTML entities

**Comment by ateesdalejr** [comment]
@csf30816 bio changing now uses `htmlspecialchars`. Is there a method that does its inverse? Like unescaping a string? I need this for usernames.

**Comment by csf30816** [comment]
Wait, do you mean like removing anything that's not A-Z/a-z/0-9? Or do you mean something that turns &amp; into &?

**Comment by ateesdalejr** [comment]
if you look at the current implementation when trying to sign in or register a user with a `'` in their name the server just gets stuck on a white screen. I think this is because the `decode_json` in slimdb chokes on it because it's malformed json.

**Comment by ateesdalejr** [comment]
The second one in your question is more like it.

**Comment by csf30816** [comment]
We should only allow A-Z/a-z/0-9/-/_ usernames then

**Comment by ateesdalejr** [comment]
bio is having the same problem as well I think. htmlspecialchars might fix it but I'm not sure.

**Comment by csf30816** [comment]
`preg_replace("/[^a-zA-Z0-9]+/", "", "TEXT-TEXT01,'  lol"); // returns TEXT-TEXT01lol` that should work.

**Comment by ateesdalejr** [comment]
Ok, that will work for usernames. I still need to fix  the problem with bio's choking with single quotes.

**Comment by csf30816** [comment]
OK, yeah. That will be a problem. So far all I can think of is replacing `'` with `\'` but that might not work :|

**Comment by ateesdalejr** [comment]
`json_encode()` may work. 👍

**Comment by csf30816** [comment]
No, JSON Encode turns an Object into JSON... I think :P

**Comment by ateesdalejr** [comment]
oh... Stackoverflow said otherwise. <https://stackoverflow.com/questions/6269188/how-to-escape-only-single-quotes#6269254>

**Comment by csf30816** [comment]
Ah, ok than I have never really used JSON_ENCODE only JSON_DECODE :)

**Comment by ateesdalejr** [comment]
OK! JS injection is no longer possible. Going to use your preg_match on the usernames next.

**Comment by csf30816** [comment]
Awesome! Soon we will have a really good (or somewhat so) user system :)

**Comment by csf30816** [comment]
Just wondering... Do you have the code that decodes the user session's here on Github? That's not very safe.

**Comment by ateesdalejr** [comment]
? Why not? It's impossible for someone to fake the sessions because they can't determine exactly when someone logged on.

**Comment by csf30816** [comment]
Yeah, did not think of that. I am not too good at security :P

**Comment by ateesdalejr** [comment]
though I was sort of dumb and published the db.slim file. 📦 good thing it only has the md5 hash of "password" in it.

**Comment by ateesdalejr** [comment]
lol <http://andrewjr.frvp.cf/user/csf>

**Comment by csf30816** [comment]
What happened to http://andrewjr.frvp.cf/user/csf30816?

**Comment by ateesdalejr** [comment]
The original username sanitizer I had stripped all numbers from your name. 👎

**Comment by csf30816** [comment]
:(

**Comment by csf30816** [comment]
That's actually pretty funny lol

**Comment by ateesdalejr** [comment]
You can still log in as `csf` if you want.

**Comment by csf30816** [comment]
OK. I will ;)

**Comment by csf30816** [comment]
xD u changed my bio :P

**Comment by ateesdalejr** [comment]
#5 Is fixed now. It keeps you from registering an account with less than 3 digits in the name as well as not allowing account names to start with digits.

**Comment by ateesdalejr** [comment]
Closing this in favor of #6.
